### ISSUE TITLE
Erlang env on Linux

### ISSUE THREAD

**Issue by ioolkos** [exograd/erl-yaml#1]
I think the Erlang default is to install in `/usr/local/{bin,lib/erlang}` on Linux too:
https://github.com/exograd/erl-yaml/blob/7ed9e54ddce76d41ebe20938be5fe15ccf695767/GNUmakefile#L29

Thanks!
I also did `sudo apt-get install libyaml-dev` to install libyaml. (This is mentioned in the readme, though)

**Comment by galdor** [comment]
`/usr/lib/erlang/usr/include` and `/usr/lib/erlang/usr/lib` are usually used by Erlang on Linux for the header files and libraries used to  build the NIF. It works at least on Archlinux and Ubuntu.

**Comment by ioolkos** [comment]
Thanks, I guess I ran into this because I build OTP releases just using defaults: https://www.erlang.org/docs/24/installation_guide/install#configuring

**Comment by galdor** [comment]
The real problem is that Erlang does not seem to provide a pkg-config file (at least I do not have one in the Archlinux package). It would be a nice contribution to OTP :)
